version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "composer dependencies"
    reviewers:
      - hasan-wajahat
    assignees:
      - ixdf-bot
