name: Format

on:
  pull_request:
    paths:
    - '**.css'
    - '**.js'
    - '**.vue'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: yarn install
      env:
        CI: true

    - name: Run formatting tool
      run: yarn format

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "✨ Apply formatting changes"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
