name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: yarn install
      env:
        CI: true

    - name: Run tests
      run: yarn test
